### PR TITLE
Change the default URL of the hub

### PR DESCRIPTION
**Pull request by jrwren**
to /.well-known/mercure

### CODE REVIEW

**Comment by jrwren** [comment]
for #182

**Comment by dunglas** [comment]
Hi @jrwren, thanks for this! Code changes are ok, but the spec must also be updated to indicate the URL `SHOULD` be `/.well-known/mercure`

**Comment by jrwren** [comment]
I looked over the spec and I don't know know where to put this information.

**Comment by dunglas** [comment]
I'll take care of this! Thanks

**Comment by dunglas** [comment]
Thanks @jrwren

**Pull request merged**
